### ISSUE TITLE
Improve resilience on redis failure

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie-site-factory#145]
## Feature Request

**Is your feature request related to a problem or unsupported use case? Please describe.**
When the app fails to connect to Redis, we get a 500 error and the site is unavailable. 

**Describe the solution you'd like**
Redis is used for sessions and page cache, so when Redis fails, we sure want to be alerted by an error log but the site should continue to work on a degraded mode:
- sessions : logged in users would be logged out and would see the public site as anonymous users
- cache : pages can be recalculated (or cached in the container via a failover memory cache backend for heavy load sites)

**Comment by jbpenrath** [comment]
#190
