### ISSUE TITLE
Static File Storage

### ISSUE THREAD

**Issue by aarajbhattarai** [openfun/richie-site-factory#236]
I am trying to store my static files in S3 bucket.I gave value to all the AWS variables but the files were not being moved so I added the extra ones. The files are stored in S3 Bucket.
AWS_ACCESS_KEY_ID = values.SecretValue()
    AWS_SECRET_ACCESS_KEY = values.SecretValue()
    AWS_STORAGE_BUCKET_NAME= ""
    AWS_S3_CUSTOM_DOMAIN = ''

    DEFAULT_FILE_STORAGE = "base.storage.MediaStorage"
    STATICFILES_STORAGE = "base.storage.CDNManifestStaticFilesStorage"
    STATIC_URL = 'https://%s/static/' % AWS_S3_CUSTOM_DOMAIN
    MEDIA_URL = 'https://%s/media/' % AWS_S3_CUSTOM_DOMAIN

    AWS_S3_REGION_NAME = values.Value("ap-south-1")

**I get this error.**

[collector 1/3] RUN apt-get update &&     apt-get install -y     rdfi  7.1s
 => [collector 2/3] RUN python manage.py collectstatic --noinput        1683.6s
 => [collector 3/3] RUN rdfind -makesymlinks true /data/static             0.3s
 => ERROR [production 1/1] COPY --from=collector /data/static/staticfiles  0.0s
------
 > [production 1/1] COPY --from=collector /data/static/staticfiles.json /data/static/:
------
failed to compute cache key: failed to walk /var/lib/docker/tmp/buildkit-mount217627317/data/static: lstat /var/lib/docker/tmp/buildkit-mount217627317/data/static: no such file or directory
ERROR: Service 'app' failed to build : Build failed
make: *** [build] Error 1

**Comment by sampaccoud** [comment]
From what I understand of your question, I think you are confusing 2 things:
- `Django` settings to configure how the app runs in production,
- `DockerFile` that builds the image.

The error you're posting happens in the `Docker` build. The reason we are collecting static files in the `Docker` build is that we are creating a custom `Nginx` image that directly contains our static files. Our deployments are then fast and we know exactly what files we are serving for each version of the app. Of course, a `CloudFront` distribution is deployed in front of `Nginx` to serve them efficiently without hitting `Nginx` centrally. The `Terraform` code to do that is provided in this project: https://github.com/openfun/richie-site-factory/tree/master/aws

I would like to clarify why it is not recommended to host your static files on S3:
- the `collectstatic` command is very slow with S3. It makes your deployments painful,
- each time a new version of the site is deployed, you will be piling up files in your bucket, leading to a messy static files folder with an associated extra cost and old static files still being available online... Of course it can be cleaned but :unamused:

Another solution if you don't want to build a custom `Nginx` image is to use [Whitenoise](http://whitenoise.evans.io). I think this is the best option if you are using a CDN.

**Comment by aarajbhattarai** [comment]
Thank you so much!! @sampaccoud

**Comment by aarajbhattarai** [comment]
Then will the static files be delivered from CloudFront when I run the project locally?

**Comment by sampaccoud** [comment]
Hello @aarajbhattarai 👋
No because the CDN is used only when the `CDN_DOMAIN` setting is set as you can see here:
https://github.com/openfun/richie-site-factory/blob/cffb0871d940297c5784f9350f7067c1f2530a5e/sites/demo/src/backend/base/storage.py#L48

If you use whitenoise, it will be another static files backend so you need to refer to the section od their documentation concerning CDN and CloudFront http://whitenoise.evans.io/en/stable/django.html#instructions-for-amazon-cloudfront

You can also look at how we switched to whitenoise on one of our other projects which is structurally similar to Richie: https://github.com/openfun/marsha/pull/882

**Comment by aarajbhattarai** [comment]
Hi @sampaccoud 
I was not aware of the benefits of serving files from nginx .
Now, I am using the default backend.
I am getting a 502 error when loading the nginx server locally.

**ERROR:**
[Error] Failed to load resource: the server responded with a status of 502 () (main.26617626c33a.css, line 0). 
https://d2xdi0fljpq0zr.cloudfront.net/static/richie/css/main.26617626c33a.css


Thank you

**Comment by sampaccoud** [comment]
502 means that either CloudFront  is not proxying to the right url or the nginx image is not running at this url. 

I'm not sure what you mean by default backend but f you are using our production settings, you have to start an nginx service using our image built by the project. Django is not configured to serve static files in this project. I was mentioning it to you as a best practice and easier way of hosting static files.

**Comment by aarajbhattarai** [comment]
Thank you!! @sampaccoud

**Comment by sampaccoud** [comment]
What solution did you find and can we close the issue?
