### ISSUE TITLE
Disappearing svg icons

### ISSUE THREAD

**Issue by sampaccoud** [openfun/richie-site-factory#296]
## Bug Report

**Problematic behavior/code**
On some of our sites, the course glimpse icons disappear on the home page section, e.g on https://www.fun-mooc.fr.

The icons color is set specifically: https://github.com/openfun/richie/blob/master/src/frontend/scss/objects/_course_glimpses.scss#L194

But it is overriden by a generic rule of the theme: 
https://github.com/openfun/richie/blob/7e2cfab70fd5ceb3f8188289e6618d708e49691e/src/frontend/scss/tools/_colors.scss#L150-L154

So the icon disappears when the chosen section variant defines a white color for `$middle-gradient-scheme`

**Expected Behavior**
The specific color set for each svg should be respected.

**Steps to Reproduce**
visit home page on https://www.fun-mooc.fr

**Environment**
- Richie version: 2.8.2
- Platform: docker

**Comment by jbpenrath** [comment]
Fixed by #297
