### ISSUE TITLE
HTML points to wrong CSS

### ISSUE THREAD

**Issue by aarajbhattarai** [openfun/richie-site-factory#301]
Hi,
My web application is pointing to the wrong CSS hash file in Production. 
I have invalidated the files in Cloudfront distribution using "/*".
Other files are pointed correctly like logo .

What can I do to solve this?

Thank you

**Comment by sampaccoud** [comment]
It's hard to help you with this little info. Can you give more details and screenshots?

**Comment by aarajbhattarai** [comment]
<img width="975" alt="Screen Shot 2021-12-20 at 9 55 55 AM" src="https://user-images.githubusercontent.com/53218772/146760441-b12b466f-49cc-40fc-897b-bb618f9fadce.png">
The code repo is at [https://github.com/aarajbhattarai/atkans-site-factory](url)

**Comment by aarajbhattarai** [comment]
I don't know what is causing this error.
If there's anything more required, please do let me know.

Thank you for you selfless help!

**Comment by jbpenrath** [comment]
Hello @aarajbhattarai.

I checked your website and stylesheet is well loading from my side. So maybe you could have some issue with the CMS cache page? 

If you logs in as administrator, did you still have the issue?

**Comment by aarajbhattarai** [comment]
Hi @jbpenrath 
You are seeing the older version of the application.
I am trying to upgrade to a new one in which I am facing the problem as mentioned above.

**Comment by aarajbhattarai** [comment]
The error was due to image pull policy in Kubernetes.
I was using 
**- imagePullPolicy: IfNotPresent**

which I changed to 

**imagePullPolicy: Always**

and it is working.

**Comment by jbpenrath** [comment]
Great to read you with your problem solved!
