### ISSUE TITLE
Redirection from non www to www

### ISSUE THREAD

**Issue by aarajbhattarai** [openfun/richie-site-factory#304]
Hi 
I observed that the funmooc website gets redirected from "funmooc.fr" to "www.funmooc.fr"

I want the same for "atkans.com" to get redirected to "www.atkans.com".Currently, I have added two hosts i.e one for "www.atkans.com" and the other for "atkans.com" in the ingress but it isn't a good practice. 
I tried adding the CName records in the DNS but it isn't working. I tried finding the solutions but was unclear.

How is your team doing it? 

Thank you

**Comment by sampaccoud** [comment]
Hey @aarajbhattarai 👋
We do create both ingresses in our kubernetes cluster. The domain without "www" is redirected by nginx. We do it with a specific app in arnold: https://github.com/openfun/arnold/tree/master/core_apps/redirect

In the DNS we declare a CNAME as you said.

**Comment by aarajbhattarai** [comment]
Hi @sampaccoud 
Thanks for the solution.
Do you know of any other alternatives other than creating a specific application for redirection?

**Comment by sampaccoud** [comment]
I would say some hosting providers proposes it as a service but you really need a webserver for this :man_shrugging:

**Comment by aarajbhattarai** [comment]
Thank you very much for your selfless help !
